apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: castercat-ingress
  namespace: castercat
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - castercatcrew.com
      secretName: castercat-tls
  rules:
    - host: castercatcrew.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: castercat
                port:
                  number: 80
