apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
  - https://raw.githubusercontent.com/kubernetes-sigs/external-dns/v0.14.0/config/crd/standard/dnsendpoints.externaldns.k8s.io.yaml
  - rbac.yaml
  - deployment.yaml
  - github-pages-dns.yaml
