apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml
  - eink-dashboard-app.yaml
  - image-updater-app.yaml
  - external-dns-app.yaml
  - castercat-app.yaml
  - website-app.yaml
